import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useJobStore } from '../store/jobStore.js';
import { 
  Sparkles, 
  MapPin, 
  Briefcase, 
  DollarSign, 
  TrendingUp, 
  Zap,
  ArrowRight,
  FileCheck,
  CheckCircle,
  HelpCircle
} from 'lucide-react';

export default function Matches() {
  const { matchedJobs, profile, fetchMatchedJobs, applications, fetchApplications, loading } = useJobStore();

  useEffect(() => {
    fetchMatchedJobs();
    fetchApplications();
  }, [fetchMatchedJobs, fetchApplications]);

  const hasResume = !!profile?.resumeUrl;
  const isApplied = (jobId) => applications.some(app => app.jobId === jobId);

  return (
    <div className="max-w-5xl mx-auto px-4 py-10 font-sans">
      {/* Header */}
      <div className="mb-8">
        <h1 className="font-heading font-extrabold text-3xl text-accent flex items-center gap-2">
          <Sparkles className="h-7 w-7 text-primary animate-pulse" />
          AI Job Recommendations
        </h1>
        <p className="text-text-muted text-sm mt-1">
          Smart matches generated by comparing your extracted resume skills against active job description requirements.
        </p>
      </div>

      {!hasResume ? (
        <div className="text-center py-16 bg-white border border-border-subtle rounded-2xl shadow-sm max-w-2xl mx-auto">
          <FileCheck className="h-14 w-14 text-slate-200 mx-auto mb-4" />
          <h3 className="font-heading font-bold text-lg text-accent">Upload Your Resume</h3>
          <p className="text-xs text-text-muted mt-2 max-w-md mx-auto leading-relaxed">
            AI recommendations are locked. Please upload your PDF resume so our LLaMA-3.3 engine can extract your technical competencies and rank active listings.
          </p>
          <Link to="/profile" className="btn-primary py-2.5 px-6 text-xs font-semibold mt-5 shadow-sm">
            Go to Resume Profile
          </Link>
        </div>
      ) : loading ? (
        <div className="flex flex-col items-center justify-center py-20 bg-white border border-border-subtle rounded-2xl shadow-sm">
          <div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin mb-4"></div>
          <p className="text-xs text-text-muted font-medium">Running LLaMA semantic matcher...</p>
        </div>
      ) : matchedJobs.length === 0 ? (
        <div className="text-center py-16 bg-white border border-border-subtle rounded-2xl shadow-sm max-w-2xl mx-auto">
          <HelpCircle className="h-14 w-14 text-slate-200 mx-auto mb-4" />
          <h3 className="font-heading font-bold text-lg text-accent">No recommendations found</h3>
          <p className="text-xs text-text-muted mt-2 max-w-md mx-auto leading-relaxed">
            Our recommendation algorithm couldn't find any job matches with overlapping skills. Try adding more skills in your profile dashboard.
          </p>
          <Link to="/profile" className="btn-outline py-2.5 px-6 text-xs font-semibold mt-5">
            Add More Skills
          </Link>
        </div>
      ) : (
        <div className="space-y-6">
          <div className="flex items-center justify-between text-xs text-text-muted px-1">
            <span>Displaying {matchedJobs.length} recommendations</span>
            <span>Sorted by highest overlap</span>
          </div>

          <div className="space-y-6">
            {matchedJobs.map((match) => {
              const applied = isApplied(match.id);
              const matchedSkills = match.matchedSkills || [];
              const requiredSkills = match.requiredSkills || [];
              const missingSkills = requiredSkills.filter(s => !matchedSkills.includes(s.toLowerCase()));
              return (
                <div key={match.id} className="premium-card p-6 md:p-8 bg-white border-slate-100 flex flex-col md:flex-row md:items-center justify-between gap-6 hover:scale-[1.005]">
                  <div className="flex-1 space-y-4">
                    {/* Job Header */}
                    <div className="flex flex-wrap items-center gap-3">
                      <h3 className="font-heading font-extrabold text-lg text-accent leading-none">{match.title}</h3>
                      <span className="bg-sky-50 border border-sky-100 text-primary text-xs font-bold px-2.5 py-0.5 rounded-full flex items-center gap-1">
                        <TrendingUp className="h-3.5 w-3.5" />
                        {match.matchPercentage}% Skill Match
                      </span>
                    </div>

                    <p className="text-xs font-semibold text-text-muted">{match.company} • {match.location}</p>

                    {/* Metadata Badges */}
                    <div className="flex flex-wrap gap-4 text-xs font-medium text-text-muted">
                      <span className="flex items-center gap-1.5">
                        <Briefcase className="h-4 w-4 text-primary" />
                        <span className="capitalize">{match.jobType}</span>
                      </span>
                      <span className="flex items-center gap-1.5">
                        <DollarSign className="h-4 w-4 text-primary" />
                        ${(match.salaryMin / 1000).toFixed(0)}k - ${(match.salaryMax / 1000).toFixed(0)}k / year
                      </span>
                    </div>

                    {/* Skill Analysis breakdown */}
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2">
                      <div className="p-3 bg-emerald-50/50 border border-emerald-100/50 rounded-xl">
                        <span className="text-[10px] text-emerald-800 font-bold uppercase tracking-wider block mb-1.5">Matching Skills</span>
                        <div className="flex flex-wrap gap-1">
                          {matchedSkills.length === 0 ? (
                            <span className="text-[10px] text-emerald-600 italic">None</span>
                          ) : (
                            matchedSkills.map(s => (
                              <span key={s} className="bg-white border border-emerald-200 text-emerald-700 text-[10px] px-2 py-0.5 rounded font-semibold">
                                {s}
                              </span>
                            ))
                          )}
                        </div>
                      </div>

                      <div className="p-3 bg-slate-50 border border-slate-100 rounded-xl">
                        <span className="text-[10px] text-text-muted font-bold uppercase tracking-wider block mb-1.5">Missing Skills</span>
                        <div className="flex flex-wrap gap-1">
                          {missingSkills.length === 0 ? (
                            <span className="text-[10px] text-emerald-700 font-bold">Perfect Match! ✓</span>
                          ) : (
                            missingSkills.map(s => (
                              <span key={s} className="bg-white border border-slate-200 text-slate-500 text-[10px] px-2 py-0.5 rounded">
                                {s}
                              </span>
                            ))
                          )}
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Actions */}
                  <div className="shrink-0 flex md:flex-col items-center justify-end gap-3 self-start md:self-center">
                    {applied ? (
                      <span className="bg-emerald-50 border border-emerald-200 text-emerald-700 text-xs font-semibold py-2.5 px-5 rounded-xl flex items-center gap-1.5">
                        <CheckCircle className="h-4 w-4" /> Applied
                      </span>
                    ) : (
                      <Link to="/jobs" className="btn-primary py-2.5 px-5 text-xs font-semibold shadow-sm">
                        View & Apply
                        <ArrowRight className="h-3.5 w-3.5" />
                      </Link>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}
